### ISSUE TITLE
ansible_fqdn problematic for getting hostname

### ISSUE THREAD

**Issue by andor-pierdelacabeza** [dj-wasabi/ansible-telegraf#105]
This is half bug report, half feature request:

**Describe the bug**

In some nodes I'm getting weird hostnames, mostly `localhost.localdomain`. Those nodes show proper configuration in `hostnamectl`.  I've seen you're using[ 'ansible_fqdn' as default](https://github.com/dj-wasabi/ansible-telegraf/blob/master/defaults/main.yml#L12).

Seems like [ansible_fqdn and ansible_hostname can give different results](https://github.com/ansible/ansible/issues/38777), and [sometimes even very weird results](https://github.com/ansible/ansible/issues/9972), as it sometimes makes DNS calls (which is not under my control in that cases) to infer that names.

**Fix proposal**

In my playbook I've added this parameter:
```yaml
 telegraf_agent_hostname: "{{ ansible_nodename }}"
```
If you don't want to change the default on this role, for fear of breaking things, maybe it should be noted on the README that users might need or want to change it on their playbooks.

**Installation method/version**
* Ansible Galaxy / 1.1.0

**Ansible Version**

```
ansible 2.8.2
  config file = /home/agonzalez/Documents/repos/monitoringdeployment/ansible.cfg
  configured module search path = ['/home/agonzalez/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/agonzalez/Documents/repos/monitoringdeployment/venv/lib/python3.7/site-packages/ansible
  executable location = /home/agonzalez/Documents/repos/monitoringdeployment/venv/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]

```

**Targetted hosts**
Concerns the following OS(es):

* Ubuntu
* Debian

**Comment by dj-wasabi** [comment]
Hi @andor-pierdelacabeza 

I updated the README.md : https://github.com/dj-wasabi/ansible-telegraf#ansible-fqdn-problematic-for-getting-hostname

Thanks! 👍
