### ISSUE TITLE
Logparser configuration

### ISSUE THREAD

**Issue by edouardkleinhans** [dj-wasabi/ansible-telegraf#111]
It's not possible to manage logparser configuration file

[[inputs.logparser]]
files = ["/var/log/messages"]
from_beginning = false
[inputs.logparser.grok]
patterns = [“invoked oom-killer”]

**Comment by dj-wasabi** [comment]
Hi @edouardkleinhans 

I created a PR for this, are you willing to test this before I merge the PR?
