### ISSUE TITLE
Broken on Ubuntu 20.04

### ISSUE THREAD

**Issue by ptheofan** [dj-wasabi/ansible-telegraf#121]
**Describe the bug**
FAILED - RETRYING: Debian | Install Telegraf package (1 retries left).

```
fatal: [sedge-01]: FAILED! => {"attempts": 3, "cache_update_time": 1588931069, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'telegraf=1.10.0-1'' failed: E: Version '1.10.0-1' for 'telegraf' was not found\n", "rc": 100, "stderr": "E: Version '1.10.0-1' for 'telegraf' was not found\n", "stderr_lines": ["E: Version '1.10.0-1' for 'telegraf' was not found"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]}
```

**Installation method/version**

Ansible Galaxy / latest

**Ansible Version**

```
ansible 2.9.7
```

**Targetted hosts**
Concerns the following OS(es):
* Ubuntu 20.04

**Comment by acamilleri** [comment]
Same problem here
I think it's a mistake on the conditional check here : https://github.com/dj-wasabi/ansible-telegraf/blob/0.12.0/tasks/Debian.yml#L7

This is fixed on master by this commit: https://github.com/dj-wasabi/ansible-telegraf/commit/b48ff6b27335a1011827b945cc29bcb686608cad
The commit was not backport to the latest release (`0.12.0`), the version of this role must be must be pin as   `b48ff6b27335a1011827b945cc29bcb686608cad` in your requirements file.

**Comment by dwerder** [comment]
There was a merge who introduced a conditianal error: https://github.com/dj-wasabi/ansible-telegraf/pull/108

This results in errors like:
`FAILED! => {"attempts": 3, "changed": false, "msg": "version number inconsistent with state=latest: telegraf=1.10.0-1"}`

And its not a Ubuntu problem. At the moment its broken for all Debian-like distros.
