### ISSUE TITLE
Setup the system for individual plugins

### ISSUE THREAD

**Issue by carlba** [dj-wasabi/ansible-telegraf#125]
**Is your feature request related to a problem? Please describe.**
It is possible to configure plugins but the dependencies are still not installed.

**Describe the solution you'd like**
I would like the role to setup the dependencies for the plugins activated. I can see that this might be outside the scope of this role. Just wanted to check if you would be willing to accepts PR:s in this direction?

**Additional context**

**Comment by dj-wasabi** [comment]
Hi @carlba 

If you think the changes adds value to use of this role so other people can benefit from it, then please do so!

**Comment by dj-wasabi** [comment]
Merged PR, will close this issue. Thanks! 👍
