### ISSUE TITLE
Fix Python package dependencies on SUSE releases

### ISSUE THREAD

**Issue by jeffmahoney** [dj-wasabi/ansible-telegraf#153]
**Describe the bug**

In order to ensure that the zypper module works, the SUSE support installs the packages containing the libxml2 and xml python modules. The naming of these packages across releases is a bit of a mess and can fail on SLE15 due to the package being named python3-libxml2-python. That name will obviously not work when Python 2 is required on SLE12 systems due to it using Python 3.4, which Ansible will not use.

**Installation method/version**

* Github / latest
**Ansible Version**

```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jeffm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Aug 31 2021, 01:23:42) [GCC]
```

**Targetted hosts**
Concerns the following OS(es):

* SLE15 SP3

**Expected behavior**
The package containing the Python libxml2 module is installed consistently across releases.

**Additional context**
I've fixed this locally and will start a PR after submitting this issue to use as a reference.

**Comment by dj-wasabi** [comment]
Will close this as a PR was provided a while ago and was merged (and released).
