### ISSUE TITLE
Add default repository handling for SUSE releases

### ISSUE THREAD

**Issue by jeffmahoney** [dj-wasabi/ansible-telegraf#154]
**Describe the bug**

The initial commit that added SUSE support to this role hard-coded the respository URL to use the openSUSE Tumbleweed build. As Tumbleweed rolled on, new requirements for glibc came with it, and the builds stopped being usable on other releases.  That was worked around in commit 3596c7b95 (Add variable for openSUSE RPM repository (#151)) but we can do better.

The repositories for the telegraf packages have well known locations on openSUSE's Open Build Service download server. We can choose from several repositories as the various Red Hat derivatives do already. In order not to break 

**Installation method/version**

* Github / latest
* 
**Ansible Version**

```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jeffm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Aug 31 2021, 01:23:42) [GCC]
```

**Targetted hosts**
Concerns the following OS(es):

Any SUSE release other than openSUSE Tumbleweed

**Expected behavior**

The appropriate repository for the release is used.

**Additional context**
It should be possible to simply add the ``obs://devel:languages:go`` repository and let zypper handle the rest, but the Ansible zypper module tries to confirm that a repository has been added using the provided URL and that fails.

I've fixed this locally and will start a PR after submitting this issue to use as a reference.

**Comment by dj-wasabi** [comment]
Will close this as a PR was provided a while ago and was merged (and released).
