### ISSUE TITLE
Failing on Debian Bookwork, telegraf recomends stable main rather than specific release

### ISSUE THREAD

**Issue by yenoromm** [dj-wasabi/ansible-telegraf#175]
**Describe the bug**
Failing on debian bookworm due to not following influxdata's recomendations

**Installation method/version**
* Ansible Galaxy / 1.1.0

**Ansible Version**

```
ansible [core 2.15.2]
  config file = /Users/xxx/git.xxx.io/ansible/ansible.cfg
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.2.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/Cellar/ansible/8.2.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

**Targetted hosts**
Concerns the following OS(es):

* Debian

**Expected behavior**
Not use specific releases, instead use the "stable main" as per telegraf's maintainer

**Additional context**
Issue showing maintainer directing people to the repo docs:
https://github.com/influxdata/telegraf/issues/13458

Repo docs:
https://repos.influxdata.com/debian/dists/

Relevant section:
```
echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list
```

**Comment by peterbaumert** [comment]
@dj-wasabi could you release a new version with those fixes?

**Comment by dj-wasabi** [comment]
Is there a way to provide a PR for this? So I can then create a new release?

**Comment by dj-wasabi** [comment]
New version (`0.14.1`) is released on the galaxy.
