### ISSUE TITLE
amazon.aws.ec2_tag_info

### ISSUE THREAD

**Issue by ThorstenHeck** [dj-wasabi/ansible-telegraf#177]
**Describe the bug**
The aws ec2 tag module does not support listing of tags anymore, use the desired amazon.aws.ec2_tag_info role instead.

**Installation method/version**

* Github / latest

**Ansible Version**

```
ansible --version
ansible [core 2.15.4]
```

**Targetted hosts**

* Ubuntu

**Expected behavior**

**Additional context**

The module "ec2_tag_module" state option "list" has been deprecated since version 4.0.0 and moved to the module "amazon.aws.ec2_tag_info"

Source:
https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_tag_module.html#parameter-state

**Comment by dj-wasabi** [comment]
Available in new (`0.14.1`) version.
