### ISSUE TITLE
multiple plugins in telegraf_plugins_extra are duplicated

### ISSUE THREAD

**Issue by haraldkoch** [dj-wasabi/ansible-telegraf#22]
When I define multiple plugins in `telegraf_plugins_extra`, the role creates a separate file for each plugin in `/etc/telegraf/telegraf.d`. However, each file lists all of the extra plugins.

The issue is that the task "Copy telegraf extra plugins" iterates over `telegraf_plugins_extra`, but the template file `telegraf-extra-plugin.conf` *also* iterates over `telegraf_plugins_extra`, causing duplicates.

I'm not quite expert enough in ansible to know how to fix this yet, but I'll try to find some time to play with it...

**Comment by dj-wasabi** [comment]
Hi @haraldkoch 

Please let me know if you need help. Otherwise I'll take a look at it and fix it.

**Comment by haraldkoch** [comment]
Okay, the obvious fix (remove the iteration inside the file) works - until you define multiple plugins with the same type (e.g. two SNMP plugins talking to different servers). In that case, the second one doesn't get instantiated in the final output.

Back to square one :)

**Comment by dj-wasabi** [comment]
@haraldkoch 

Can you confirm that with the merge of a PR in the last few days that this issue is solved now?

**Comment by haraldkoch** [comment]
@dj-wasabi Worked perfectly on my test server, yes.

**Comment by dj-wasabi** [comment]
Thanks! Will close this issue and create a release in the next few days.
