### ISSUE TITLE
PIP dependencies conflicting with native yum packages

### ISSUE THREAD

**Issue by christopherobin** [dj-wasabi/ansible-telegraf#28]
For the RedHat version the playbook installs a bunch of pip dependencies which, as far as I can see, are only used by tests (since Telegraf is written in go).

Those dependencies are causing issues with packages that might actually depend for example on the `python-urllib3` yum package since yum will fail if files installed by the package already exist on the system.

Would it be possible to remove those dependencies? Or at least move them to the `test.yml` test playbook?

**Comment by dj-wasabi** [comment]
Hi @christopherobin 

Yes, the role should only install packages needed for correct usage of the application. If the pip packages are only used for testing, then it should be removed from the role and places in the `playbook.yml`.
