### ISSUE TITLE
A new Release for the .deb package url change

### ISSUE THREAD

**Issue by stvnwrgs** [dj-wasabi/ansible-telegraf#3]
If you download the role from galaxy, the role breaks because 0.3.0 (the actual version) does not have the fix for the changed URL for .deb packages. A new release should fix that.

**Comment by dj-wasabi** [comment]
Hi,

You are right. Busy with one small fix and will create new tag and release.

**Comment by dj-wasabi** [comment]
I just pushed 0.4.0 to github and the Galaxy.
