### ISSUE TITLE
PR #46 break telegraf "Multiple inputs of the same type"

### ISSUE THREAD

**Issue by gaelL** [dj-wasabi/ansible-telegraf#48]
Hello,

The last merged PR https://github.com/dj-wasabi/ansible-telegraf/pull/46 seems to don't allow anymore to use several time the same input plugin.

This PR make the input name based on a dict key, which can't be duplicated.

```
+[[inputs.{{ item.key }}]]
```

Ref in Telegraf doc : an input could be called several time https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#multiple-inputs-of-the-same-type

This is important for some input plugin like : https://github.com/influxdata/telegraf/issues/2294#issuecomment-290679049

Behavior added in ansible-telegraf here https://github.com/dj-wasabi/ansible-telegraf/pull/46

Regards

**Comment by tjend** [comment]
Yes, this has broken that functionality.

It might be better to use the unique dict key as the plugin name and filename, and have a value within the dict to override the plugin name in the case of duplicates. Let me think how best this might be handled.

**Comment by tjend** [comment]
I believe https://github.com/dj-wasabi/ansible-telegraf/pull/50 should fix the issue. Please add a 'plugin:' key to the dict.

The input name is now set like this:
`[[inputs.{{ item.value.plugin | default(item.key) }}]]`
