### ISSUE TITLE
Deleting extra plugins doesn't delete them

### ISSUE THREAD

**Issue by Ismael** [dj-wasabi/ansible-telegraf#8]
If I configure a telegraf_plugins_extra, run ansible, delete the plugin and run ansible again, the plugin stays on the machine.

The "easy" way out is to just nuke /etc/telegraf/telegraf.d/*, though that will force to restart telegraf
Do this before copying the extra plugins:

```
- name: "Delete extra plugins"
  shell: "rm -rf /etc/telegraf/telegraf.d/*"

```

**Comment by dj-wasabi** [comment]
Hi @Ismael 

In the last few days a PR was accepted and merge that fixes this issue. Would you please verify and if ok, close the issue? When this issue is verified, I'll create a new release.

**Comment by Ismael** [comment]
Only issue I see is that when migrating from an older release, you keep the old files. So to use the new release, you have to be sure that you deleted the old conf files.
Otherwise looks good.

**Comment by dj-wasabi** [comment]
Thank you for this comment. I'll make an upgrade notification in the README.md to address this. Thanks again!
