### ISSUE TITLE
Install telegraf from package file instead of repository

### ISSUE THREAD

**Issue by vignemail1** [dj-wasabi/ansible-telegraf#89]
On old hosts with old SSL library, it is impossible to negotiate TLS with the repository. Hosts can't always be updated because of applications dependencies.
An installation from package files is mandatory in these cases.

**Describe the solution you'd like**
A way to install telegraf from pre-downloaded package files using ansible variables.
For example: 
- ```telegraf_install_mode```: ```"online"``` or ```"offline"```
- ```telegraf_offline_apt_package```: ```"/path/to/telegraf_1.9.4-1_amd64.deb"```
- ```telegraf_offline_yum_package```: ```"/path/to/telegraf-1.9.4-1.x86_64.rpm"```
- ...

**Comment by dj-wasabi** [comment]
Hi @vignemail1 

I created a PR that would help fixing this issue. Can you take a look and see if this works for you (And if all is clear 😄 )? Thanks! 👍
