### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by langerma** [dj-wasabi/ansible-telegraf#99]
**adding support for FreeBSD via pkg**
as telegraf is in the official pkg repos for FreeBSD i guess it would be easy to adopt another Platform. I started to port your role to FreeBSD, but my ansible knowledge is very basic.

**Comment by dj-wasabi** [comment]
Hi @langerma 

I'm all for adding support for more platforms. I do have however, not that much experience with FreeBSD. Is there an possibility that you create a fork of this repository and can start with something? Or do you prefer that I (or someone else makes an attempt on this?)

Last question: if there is a PR available with FreeBSD support, do you have a possibility to verify that it works in your case? (I'll make sure that there is also an test available that works with FreeBSD, if an Docker image is available)

**Comment by langerma** [comment]
i can try to beef up my fork, but as said i am not really good in writing ansible :-)

**Comment by dj-wasabi** [comment]
@langerma No worries, otherwise I do an attempt. 😄

**Comment by langerma** [comment]
with #100 i added basic FreeBSD support (dirty shell hack to enable and configure extra plugin dict)
